ALTER TABLE livestreams ALTER COLUMN description TYPE VARCHAR(1000);
ALTER TABLE livestreams ALTER COLUMN thumbnail_url TYPE VARCHAR(2048);

ALTER TABLE vods ALTER COLUMN description TYPE VARCHAR(1000);

ALTER TABLE vod_comments ALTER COLUMN content TYPE VARCHAR(2000);
