spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/ThNam203/letslive-configs.git"
          default-label: main
          timeout: 10
          clone-on-start: true
          force-pull: true
          username:
          password: 
  #main:
    #show_banner: "off"

server:
  port: 8181

logging:
  level:
    root: ERROR
    org:
      springframework:
        cloud: ERROR
        web: ERROR

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
