_format_version: "3.0"
services:
  - name: User
    host: user.service.consul
    port: 7778
    path: /v1
    retries: 5
    connect_timeout: 60000
    read_timeout: 60000
    write_timeout: 60000
    routes:
      - name: Users
        protocols:
          - http
          - https
        paths:
          - /users
        strip_path: false
        preserve_host: false
        https_redirect_status_code: 426
        request_buffering: true
        response_buffering: true
      - name: User
        protocols:
          - http
          - https
        paths:
          - /user
        strip_path: false
        preserve_host: false
        https_redirect_status_code: 426
        request_buffering: true
        response_buffering: true
      - name: Upload_File # TODO: change this to other services?
        protocols:
          - http
          - https
        paths:
          - /upload-file
        strip_path: false
        preserve_host: false
        https_redirect_status_code: 426
        request_buffering: true
        response_buffering: true

  - name: Auth
    host: auth.service.consul
    port: 7777
    path: /v1/auth
    retries: 5
    connect_timeout: 60000
    read_timeout: 60000
    write_timeout: 60000
    routes:
      - name: Auth_Routes
        protocols:
          - http
          - https
        paths:
          - /auth
        strip_path: true
        preserve_host: false
        https_redirect_status_code: 426
        request_buffering: true
        response_buffering: true

  - name: Livestream
    host: livestream.service.consul
    port: 7781
    path: /v1
    retries: 5
    connect_timeout: 60000
    read_timeout: 60000
    write_timeout: 60000
    routes:
      - name: Livestream_Routes
        protocols:
          - http
          - https
        paths:
          - /livestream
          - /livestreams
          - /livestreamings
          - /popular-vods
          - /is-streaming
        strip_path: false
        preserve_host: false
        https_redirect_status_code: 426
        request_buffering: true
        response_buffering: true

  - name: Chat
    host: chat.service.consul
    port: 7780
    path: /v1
    connect_timeout: 60000
    read_timeout: 60000
    write_timeout: 60000
    routes:
      - name: Chat_Socket
        paths:
          - /ws
        strip_path: false
        protocols:
          - http
          - https
      - name: Chat_Messages
        protocols:
          - http
          - https
        paths:
          - /messages
        strip_path: false
        preserve_host: false
        https_redirect_status_code: 426
        request_buffering: true
        response_buffering: true

  - name: MinIO
    host: minio.service.consul
    port: 9000
    path: /
    connect_timeout: 10000
    read_timeout: 10000
    write_timeout: 10000
    routes:
      - name: MinIO_Get_File_Route
        protocols:
          - http
          - https
        paths:
          - /files
        strip_path: true

  - name: Transcode_Service
    host: transcode.service.consul
    port: 8889
    path: /static
    connect_timeout: 10000
    read_timeout: 10000
    write_timeout: 10000
    routes:
      - name: Transcode_Get_File_Route
        protocols:
          - http
          - https
        paths:
          - /transcode
        strip_path: true

consumers:
  - username: "authenticated users"
    keyauth_credentials:
      - key: "authenticated users"
    jwt_secrets:
      - key: "authenticated users"
        secret: "access_token_secret"
        algorithm: "HS256"

plugins:
  - name: jwt
    enabled: true
    config:
      claims_to_verify:
        - exp
      cookie_names:
        - ACCESS_TOKEN
      key_claim_name: consumer
      run_on_preflight: true
    service: User
  - name: jwt
    enabled: true
    config:
      claims_to_verify:
        - exp
      uri_param_names:
        - token
      cookie_names:
        - ACCESS_TOKEN
      key_claim_name: consumer
      run_on_preflight: true
    service: Chat

  - name: cors
    enabled: true
    config:
      origins: ["*"]
      headers: ["Content-Type", "Authorization", "Cache", "Accept", "Cache-Control", "X-Requested-With"]
      exposed_headers: ["Sec-WebSocket-Accept", "Upgrade", "Connection"]
      credentials: true
      max_age: 3600
      preflight_continue: false
