server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: livestream-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: livestream-service-log
          __path__: /var/log/livestream_service.log  # Log file path inside the container

