package constants

const DEFAULT_REQUEST_PAGE_QUERY_MIN_VALUE = 0
const DEFAULT_REQUEST_LIMIT_QUERY_MIN_VALUE = 1
const DEFAULT_REQUEST_LIMIT_QUERY_MAX_VALUE = 20

const CONTEXT_REQUEST_ID_KEYNAME = "requestId"
