package constants

const REQUEST_PAGE_QUERY_DEFAULT_MIN_VALUE = 0
const REQUEST_LIMIT_QUERY_DEFAULT_MIN_VALUE = 1
const REQUEST_LIMIT_QUERY_DEFAULT_MAX_VALUE = 20

const CONFIG_SERVER_DEFAULT_RELOAD_INTERVAL = 60000 // milli

const CONTEXT_REQUEST_ID_KEYNAME = "requestId"
